title: The Routing Loop
description: Weekly AWS Networking Twitch Show

color-scheme: "mediumseagreen" # the scheme can be any HEX code like "#00aa55"

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - .sass-cache

future: true